version: '2'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: app
      dockerfile: Dockerfile
    links:
    - api
    environment:
      API_URL: "http://localhost:8003/_/"
      API_NAME: "My API"
    ports:
    - "8001:8080"
    privileged: true
    container_name: app
  
  api:
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      MYSQL_PASSWORD: directus
      MYSQL_DATABASE: directus
      MYSQL_HOST: db
      MYSQL_USER: directus
    ports:
    - "8003:8080"
    privileged: true
    container_name: api


  #######################################
  # MySQL server
  #######################################
  db:
    build:
      context: db
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: directus
      MYSQL_PASSWORD: directus
      MYSQL_DATABASE: directus
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    container_name: db

  #######################################
  # PHPMyAdmin
  #######################################
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
    - "8002:80"
    links:
    - db
    depends_on:
    - db
    container_name: pma
